### ISSUE TITLE
下载源码，运行模型报错

### ISSUE THREAD

**Issue by chensvm** [baidu/Senta#32]
INFO: 07-22 21:55:27: lanch.py:77 * 140402907469632 nranks: 1
2020-07-22 21:55:34,702-INFO: proc 0 run failed
INFO: 07-22 21:55:34: lanch.py:112 * 140402907469632 proc 0 run failed
Traceback (most recent call last):
  File "./lanch.py", line 130, in <module>
    main(lanch_args)
  File "./lanch.py", line 123, in main
    start_procs(args)
  File "./lanch.py", line 114, in start_procs
    cmd=cmds[i])
subprocess.CalledProcessError: Command '['/home/yangchen06/anaconda3/envs/paddle/bin/python', '-u', './train.py', '—param_path', './config/ernie_1.0_skep_large_ch.Chnsenticorp.cls.json', '—log_dir', './log']' returned non-zero exit status 1.

**Comment by xiaosheng123XIAO** [comment]
请问解决了吗，我也遇到同样问题啦

**Comment by Pengjm777** [comment]
> INFO：
> 07-22 21:55:27 ：lanch.py​​:77 * 140402907469632 nranks：1 2020-07-22 21：55：34,702-INFO：proc 0运行失败
> INFO：07-22 21:55:34 ：lanch的.py：112 * 140402907469632 PROC 0运行失败
> 回溯（最近通话最后一个）：
> 文件“./lanch.py​​”，线130，在
> 主（lanch_args）
> 文件“./lanch.py​​”，线路123，在主
> start_procs （args）
> 文件“ ./lanch.py​​”，第114行，位于start_procs
> cmd = cmds [i]）
> 子进程中。CalledProcessError：命令'['/ home / yangchen06 / anaconda3 / envs / paddle / bin / python'，'- u'，'。/ train.py'，'-param_path'，'。/ config / ernie_1.0_skep_large_ch.Chnsenticorp.cls.json'，'-log_dir'，'。/ log']'返回非零退出状态1。

请问解决了吗，我也遇到了一样的问题

**Comment by AlanLinZhizhou** [comment]
我也是同样的问题，有人解决了么

**Comment by wyxscir** [comment]
我也有这个问题，大家有人解决吗

**Comment by zhuliwen** [comment]
我也有这个问题，大家解决了吗
