### ISSUE TITLE
Download ABSA Model Files

### ISSUE THREAD

**Issue by ryandgoldenberg1** [baidu/Senta#51]
How can I download the model files for the trained aspect based sentiment classification? Following along with the quick tour in the README [(link)](https://github.com/baidu/Senta/blob/master/README.en.md#quick-tour), I get the following error

 ```bash
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from senta import Senta
>>> my_senta = Senta()
>>> use_cuda=False
>>> my_senta.init_model(model_class="roberta_skep_large_en", task="aspect_sentiment_classify", use_cuda=use_cuda)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/workspace/misc/senta/Senta/senta/train.py", line 205, in init_model
    param_dict = from_file(data_params_path)
  File "/home/ryan/workspace/misc/senta/Senta/senta/utils/params.py", line 47, in from_file
    file_dict = json.loads(evaluate_file(filename), strict=False)
  File "/home/ryan/workspace/misc/senta/Senta/senta/utils/params.py", line 42, in evaluate_file
    with open(filename, "r") as evaluation_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ryan/workspace/misc/senta/Senta/senta/model_files/roberta_skep_large_en.absa_laptops.cls/save_inference_model/inference_step_74/infer_data_params.json'
```

I installed the package using the "From source" instructions [here](https://github.com/baidu/Senta/blob/master/README.en.md#from-source). My system is Ubuntu 20.04. Please let me know if you need any other info to help fix this.

**Comment by JoJoJun** [comment]
me too! I get this problem too! Have you found any way to solve it ?
