### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'

### ISSUE THREAD

**Issue by ryze124** [baidu/Senta#59]
## environment： 

- Windows 10 x64
- python version：anaconda Python 3.8.3
- paddlepaddle==1.8.5

## command
`pip install Senta -i https://mirror.baidu.com/pypi/simple`

## output
`
Processing c:\users\11031\documents\doc\pyltp\senta
Collecting nltk==3.4.5
  Using cached nltk-3.4.5.zip (1.5 MB)
Collecting numpy==1.14.5
  Using cached numpy-1.14.5.zip (4.9 MB)
Collecting scikit-learn==0.20.4
  Using cached scikit-learn-0.20.4.tar.gz (11.7 MB)
Requirement already satisfied: scipy>=0.13.3 in d:\software\anaconda\lib\site-packages (from scikit-learn==0.20.4->Senta==2.0.0) (1.5.0)
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\software\anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\11031\\AppData\\Local\\Temp\\pip-install-4_uufyts\\sentencepiece_18e2d198d8004a81bf0d73416d152414\\setup.py'"'"'; __file__='"'"'C:\\Users\\11031\\AppData\\Local\\Temp\\pip-install-4_uufyts\\sentencepiece_18e2d198d8004a81bf0d73416d152414\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\11031\AppData\Local\Temp\pip-pip-egg-info-t0ekqrkf'
         cwd: C:\Users\11031\AppData\Local\Temp\pip-install-4_uufyts\sentencepiece_18e2d198d8004a81bf0d73416d152414\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\11031\AppData\Local\Temp\pip-install-4_uufyts\sentencepiece_18e2d198d8004a81bf0d73416d152414\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "D:\software\anaconda\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by ryze124** [comment]
这个错误是安装依赖sentencepiece发生的
