### ISSUE TITLE
No module named 'senta'

### ISSUE THREAD

**Issue by wyfSunflower** [baidu/Senta#64]
python -m pip install Senta
Requirement already satisfied: Senta in /home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages (1.0.3)
from senta import Senta
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/mingzhu/Pictures/pycharm-2019.3.4/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'senta'

**Comment by liuchenbaidu** [comment]
同样发现。

**Comment by jtyoui** [comment]
安装`senta`报错：No such file or directory: '..\\VERSION'
```bash
PS C:\Users\Lenovo\Desktop\go学习> pip install senta
Collecting senta
  Using cached Senta-2.0.0-py3-none-any.whl (178 kB)
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-1uzrx18m\\sentencepiece_5bc5521a3c61478ba79a1267454b1efd\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-1uzrx18m\\sentencepiece_5bc5521a3c61478ba79a1267454b1efd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Lenovo\AppData\Local\Temp\pip-pip-egg-info-nmu6xqsu'
         cwd: C:\Users\Lenovo\AppData\Local\Temp\pip-install-1uzrx18m\sentencepiece_5bc5521a3c61478ba79a1267454b1efd\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-install-1uzrx18m\sentencepiece_5bc5521a3c61478ba79a1267454b1efd\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "c:\program files\python38\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1b/87/c3c2fa8cbec61fffe031ca9f0da512747520bec9be7f886f748457daac31/sentencepiece-0.1.83.tar.gz#sha256=d194cf7431dd87798963ff998380f1c02ff0f9e380cc922a07926b69e21c4e2b (from https://pypi.org/simple/sentencepiece/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting senta
  Using cached Senta-1.0.3-py2.py3-none-any.whl (6.2 MB)
Installing collected packages: senta
Successfully installed senta-1.0.3
````

**Comment by xszqxszq** [comment]
新老版本Senta大小写有区别，试试`from Senta import Senta`

**Comment by xszqxszq** [comment]
pip直接安装的Senta很有可能是老版本，建议自行clone编译安装

**Comment by jiangxinke** [comment]
逆天，哈哈，是Senta
