### ISSUE TITLE
paddlepaddle、paddlehub安装成功senta运行时报错

### ISSUE THREAD

**Issue by smartnaive** [baidu/Senta#65]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\senta\common\register.py", line 87, in import_modules
    importlib.import_module(full_name)
  File "D:\Anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda\lib\site-packages\senta\training\base_trainer.py", line 22, in <module>
    from paddle.fluid.incubate.fleet.parameter_server.distribute_transpiler import fleet
  File "D:\Anaconda\lib\site-packages\paddle\fluid\incubate\fleet\parameter_server\distribute_transpiler\__init__.py", line 39, in <module>
    from paddle.fluid.incubate.fleet.parameter_server.ir.public import get_sparse_tablenames
  File "D:\Anaconda\lib\site-packages\paddle\fluid\incubate\fleet\parameter_server\ir\public.py", line 26, in <module>
    from paddle.fluid.core import CommContext
ImportError: cannot import name 'CommContext' from 'paddle.fluid.core_avx' (D:\Anaconda\lib\site-packages\paddle\fluid\core_avx.pyd)
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\senta\common\register.py", line 87, in import_modules
    importlib.import_module(full_name)
  File "D:\Anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda\lib\site-packages\senta\training\custom_trainer.py", line 12, in <module>
    from paddle.fluid.incubate.fleet.parameter_server.distribute_transpiler import fleet
  File "D:\Anaconda\lib\site-packages\paddle\fluid\incubate\fleet\parameter_server\distribute_transpiler\__init__.py", line 39, in <module>
    from paddle.fluid.incubate.fleet.parameter_server.ir.public import get_sparse_tablenames
  File "D:\Anaconda\lib\site-packages\paddle\fluid\incubate\fleet\parameter_server\ir\public.py", line 26, in <module>
    from paddle.fluid.core import CommContext
ImportError: cannot import name 'CommContext' from 'paddle.fluid.core_avx' (D:\Anaconda\lib\site-packages\paddle\fluid\core_avx.pyd)

**Comment by nvliajia** [comment]
这个应该是numpy版本的问题，你把numpy版本降到1.14.5应该就可以了，但是另外的问题就出现了，不过现在虽然报错了，但是模型能预测...

**Comment by JohnnyYuan93** [comment]
> 这个应该是numpy版本的问题，你把numpy版本降到1.14.5应该就可以了，但是另外的问题就出现了，不过现在虽然报错了，但是模型能预测...

我的numpy就是1.14.5，但还是有这个报错

**Comment by JohnnyYuan93** [comment]
请问这个问题解决了么，我也遇到了
