### ISSUE TITLE
源码安装为什么也报错

### ISSUE THREAD

**Issue by ArlanCooper** [baidu/Senta#81]
git clone https://github.com/baidu/Senta.git
cd Senta
python -m pip install .

报错的是:
ERROR: Command errored out with exit status 1:
   command: /Users/cooper/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/np/pjvnrzpj65q2p4gv1pfh8nqc0000gn/T/pip-install-e5bm6go8/sentencepiece_0bd93c61be5947c3a40d500b652fa2ec/setup.py'"'"'; __file__='"'"'/private/var/folders/np/pjvnrzpj65q2p4gv1pfh8nqc0000gn/T/pip-install-e5bm6go8/sentencepiece_0bd93c61be5947c3a40d500b652fa2ec/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/np/pjvnrzpj65q2p4gv1pfh8nqc0000gn/T/pip-pip-egg-info-ztpsjom6
       cwd: /private/var/folders/np/pjvnrzpj65q2p4gv1pfh8nqc0000gn/T/pip-install-e5bm6go8/sentencepiece_0bd93c61be5947c3a40d500b652fa2ec/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/np/pjvnrzpj65q2p4gv1pfh8nqc0000gn/T/pip-install-e5bm6go8/sentencepiece_0bd93c61be5947c3a40d500b652fa2ec/setup.py", line 29, in <module>
      with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
    File "/Users/cooper/opt/anaconda3/lib/python3.8/codecs.py", line 905, in open
      file = builtins.open(filename, mode, buffering)
  FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
  ----------------------------------------
WARNING: Discarding http://mirrors.aliyun.com/pypi/packages/1b/87/c3c2fa8cbec61fffe031ca9f0da512747520bec9be7f886f748457daac31/sentencepiece-0.1.83.tar.gz#sha256=d194cf7431dd87798963ff998380f1c02ff0f9e380cc922a07926b69e21c4e2b (from http://mirrors.aliyun.com/pypi/simple/sentencepiece/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.83 (from senta) (from versions: 0.0.0, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.83, 0.1.86, 0.1.90, 0.1.91, 0.1.92, 0.1.94, 0.1.95, 0.1.96)
ERROR: No matching distribution found for sentencepiece==0.1.83

这是什么问题呀？请问这边在码云上有仓库吗？github有点慢

**Comment by Nevesorez** [comment]
同样的报错，请问解决了吗？
